version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.31.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  blackbox-exporter:
    image: prom/blackbox-exporter:v0.19.0
    volumes:
      - ./blackbox.yml:/etc/prometheus/blackbox_files/blackbox.yml
    ports:
      - "9115:9115"
    depends_on:
      - prometheus
